name: basenji_kidney_finemapping
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - matplotlib
  - numpy
  - seaborn
  - h5py
  - scikit-learn
  - scipy
  - tqdm
  - pandas
  - cython
  - packaging
  - python=3.8
  - astropy
  - statsmodels
  - networkx
  - pillow
  - pybigwig
  - joblib
  - natsort
  - intervaltree
  - pysam
  - tabulate
  - pip
  - pybedtools
  - typeguard
